language: android
jdk: oraclejdk8
cache: false
sudo: true

android:
 components:
  - platform-tools
  - tools
  - build-tools-24.0.0
  - android-23
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository

script:
 - ./gradlew connectedAndroidTest --stacktrace

before_install:
 - chmod +x gradlew

licenses:
 - 'android-sdk-preview-license-.+'
 - 'android-sdk-license-.+'
 - 'google-gdk-license-.+'
